GithubTest figth

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,7 +27,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: 3.10.11
+          python-version: '3.10.11'
 
       - name: Install dependencies
         run: |
@@ -41,9 +41,28 @@ jobs:
             sleep 1
           done
 
-      - name: Run tests
+      - name: Run migrations
         env:
           DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
         run: |
           python manage.py migrate
-          pytest test/test_about.py
+
+      - name: Check for test file existence
+        run: |
+          if [ ! -f test/test_about.py ] && [ ! -f tests/test_about.py ]; then
+            echo "Test file not found in expected locations."
+            exit 1
+          fi
+
+      - name: Run tests
+        env:
+          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
+        run: |
+          if [ -f test/test_about.py ]; then
+            pytest test/test_about.py
+          elif [ -f tests/test_about.py ]; then
+            pytest tests/test_about.py
+          else
+            echo "No test file found"
+            exit 1
+          fi
